
services:
  cocktail-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocktail-java-app
    depends_on:
      - mysql
      - keycloak
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/cocktail-realm
    networks:
      - cocktail-network
    restart: unless-stopped

  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: cocktail-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=init
      - MYSQL_USER=cocktail_user
      - MYSQL_PASSWORD=cocktail_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - cocktail-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    networks:
      - cocktail-network
    restart: unless-stopped

networks:
  cocktail-network:
    driver: bridge

volumes:
  mysql_data:
